# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI
on: push
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        mode: ["", "--release"]
        toolchain: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: ${{ matrix.toolchain }}
          args: ${{ matrix.mode }} --verbose
      - uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: ${{ matrix.toolchain }}
          args: ${{ matrix.mode }} --verbose
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- --deny clippy::all --deny clippy::pedantic --deny clippy::cargo
